import type { Lang } from "./ui";

export interface Project {
  tag: string;
  title: string;
  description: string;
}

interface ProjectEntry {
  sv: Project;
  en: Project;
}

const projectEntries: ProjectEntry[] = [
  {
    sv: { tag: "AI-agent", title: "Community Assistant", description: "Min bostadsrättsförening fick samma frågor om och om igen. Jag byggde en AI-assistent som plockar upp inkommande mejl, matchar dem mot tidigare ärenden och <em>föreslår ett svar</em> baserat på hur styrelsen svarat förut. Styrelsemedlemmen godkänner eller ändrar — klart.<br><br>Byggt på <em>Akka SDK</em> med event sourcing, integrerat med <em>Gmail</em> och <em>Google Sheets</em>. En <em>SmolLM2-135M</em> nano-LLM hanterar jobbet — lätt nog att inte kräva en stor modell.<br><br>Testning via en <em>3-stegs-strategi</em>: dummy-LLM:er (snabba, deterministiska), nano-modellen som realistiskt mellanlager, och produktionsmodellen för slutlig kvalitetskontroll." },
    en: { tag: "AI Agent", title: "Community Assistant", description: "My housing community kept receiving the same questions by email. I built an AI assistant that picks up incoming emails, matches them against previous tickets, and <em>suggests a reply</em> based on how the board answered before. The board member approves or amends — that's it.<br><br>Built on the <em>Akka SDK</em> with event sourcing, integrated with <em>Gmail</em> and <em>Google Sheets</em>. A <em>SmolLM2-135M</em> nano LLM handles the job — light enough to not need a large model.<br><br>Tested with a <em>3-tier strategy</em>: dummy LLMs (fast, deterministic), the nano model as a realistic middle tier, and the production model for final confidence checks." },
  },
  {
    sv: { tag: "Infrastruktur", title: "Pi-PAI", description: "Det började med att jag ville köra Claude Code på distans — och insåg att en <em>Raspberry Pi</em> kunde hantera det mesta av mitt rutinarbete. Jag satte upp fjärrstyrd agentorkestrering på en Pi 4 och styrde det från mobilen via en app som heter <em>Happy</em>, som också gav mig röststyrning. Det kändes futuristiskt. Föreställ dig att köra bil och dirigera din AI-besättning som om du stod på bryggan på ett rymdskepp.<br><br>Jag byggde en <em>MCP-server</em> som kontrollplan: en Claude Code-instans som kunde starta och stoppa andra Claude Code-sessioner baserat på vad som behövde göras. Varje agent hade tillgång till <em>GitHub</em> och kunde självständigt köra tester, skapa pull requests och fortsätta arbeta medan jag var borta från datorn.<br><br>Hela setupen provisioneras med <em>Ansible</em> — reproducerbar infrastruktur som jag kan deploya på kraftigare hårdvara, fler maskiner eller hos en kund." },
    en: { tag: "Infrastructure", title: "Pi-PAI", description: "It started with wanting to run Claude Code remotely — and realizing a <em>Raspberry Pi</em> could handle most of my menial work. I set up remote agent orchestration on a Pi 4 and accessed it from my phone through an app called <em>Happy</em>, which also gave me voice control. It felt futuristic. Imagine driving your car and directing your AI crew like you're on the bridge of a starship.<br><br>I built an <em>MCP server</em> as a control plane: one Claude Code instance that could start and stop other Claude Code sessions based on what needed to be done. Each agent had access to <em>GitHub</em> and could independently run tests, create pull requests, and keep working while I was away from the computer.<br><br>The whole setup is provisioned with <em>Ansible</em> — reproducible infrastructure I can redeploy on bigger hardware, more machines, or at a client site." },
  },
  {
    sv: { tag: "Legacyräddning", title: "DLL-dekompilering", description: "En kund startade om sin servermjukvara var 15:e minut. Orsaken: ett kritiskt <em>race condition</em> i underhållslösa leverantörs-DLL:er — och det fanns ingen källkod.<br><br>Jag körde en dekompilator på DLL-filerna, vilket gav källkod som var ungefär 80% korrekt — resten trasigt på grund av binärernas ålder. Sedan en <em>3-fasprocess</em>: först byggde jag en testsvit mot den befintliga setupen som verifierade all mjukvarans funktionalitet. Sedan fixade jag den dekompilerade koden tills varje test passerade. Slutligen genomförde jag planen för att lösa själva samtidighetsproblemet.<br><br>Det fungerade — och låste upp en betydande intäktsström för min kund. Deployad via <em>Tailscale</em> till <em>5 kundsajter</em> med 3 rollback-strategier." },
    en: { tag: "Legacy Rescue", title: "DLL Decompilation", description: "A client was restarting their server software every 15 minutes. The cause: a critical <em>race condition</em> in unmaintained vendor DLLs — and there was no source code.<br><br>I ran a decompiler on the DLLs, which produced source code that was roughly 80% correct — the rest broken by the age of the binaries. Then a <em>3-phase process</em>: first, I built a test suite against the existing setup that asserted all the software's functionality. Second, I fixed the decompiled code until every test passed. Third, I executed the plan for solving the concurrency issue itself.<br><br>It worked — and unlocked a significant revenue stream for my client. Deployed over <em>Tailscale</em> to <em>5 customer sites</em> with 3 rollback strategies." },
  },
  {
    sv: { tag: "Modernisering", title: "Legacy-schackverktyg: omskrivning", description: "Jag skulle använda ett verktyg för att lotta ett schackturneringsfält. När jag försökte ladda ner det var det inte tillgängligt längre. Verktyget hade varit legacy sedan 2018, men det används fortfarande av många klubbar för sin enkelhet. <em>Lottning i schack är förvånansvärt komplicerat</em> — algoritmerna som bestämmer parningar är mjukvarans kärnvärde.<br><br>Jag hittade desktopappen på min dator och insåg: det här borde finnas på webben. Källkoden levererades med mjukvaran, så jag kopplade isär frontenden från databasoperationerna och skapade en webbsajt som interagerade via ett REST-lager med den ursprungliga Java-lottningslogiken.<br><br>Sedan byggde jag <em>snapshot-tester av alla möjliga lottningspermutationer</em> — över 200 snapshots av hur databasen förändras under en turnering. Med det skyddsnätet på plats portade jag hela backenden till frontenden med <em>sql.js</em> — varje snapshot-test passerade vid första körningen. Hela applikationen körs nu <em>offline i webbläsaren</em> — ingen backend behövs.<br><br><a href=\"https://lotta-web.bernting.se/?tab=pairings\" target=\"_blank\" rel=\"noopener noreferrer\">lotta-web.bernting.se</a>" },
    en: { tag: "Modernization", title: "Legacy Chess Tool Rewrite", description: "I was going to use a tool to seed a chess tournament. When I went to download it, it wasn't available anymore. The tool had been legacy since 2018, but it's still used by many clubs for its simplicity. <em>Seeding in chess is surprisingly complicated</em> — the algorithms that determine pairings are the core value of this software.<br><br>I found the desktop app on my machine and realized: this should be on the web so anyone can access it without running Java. The source code was shipped with the software, so I decoupled the frontend from the database operations and created a website interacting through a REST layer with the original Java seeding logic.<br><br>Then I built <em>snapshot tests of all possible seeding permutations</em> — over 200 snapshots of how the database changes during a tournament. With that safety net in place, I ported the entire backend into the frontend with <em>sql.js</em> — every snapshot test passing on the first run. The whole application now runs <em>offline in the browser</em> — no backend needed.<br><br><a href=\"https://lotta-web.bernting.se/?tab=pairings\" target=\"_blank\" rel=\"noopener noreferrer\">lotta-web.bernting.se</a>" },
  },
  {
    sv: { tag: "Open Source", title: "adr-lint", description: "Hur sätter man tekniska riktningar i ett team där både människor och AI-agenter bidrar? Jag byggde <em>adr-lint</em> — det låter dig definiera regelverk genom <em>Architectural Decision Records</em>, som sedan matas till en kortlivad LLM-agent vars uppgift är att bedöma om dina kodändringar lever upp till varje ADR.<br><br>Teamets <em>processer</em> är viktigare än själva verktyget — adr-lint gör bara processen möjlig att automatisera.<br><br>Jag tillämpade samma princip när jag skrev en publicerad artikel om AI och tillit: <em>15 ADR:er</em> definierade ramarna innan en mening var skriven, och en agent per ADR granskade var och en av <em>22 utkast</em> oberoende. Open source." },
    en: { tag: "Open Source", title: "adr-lint", description: "How do you set technical direction in a team where both humans and AI agents contribute? I built <em>adr-lint</em> — it lets you define rule sets via <em>Architectural Decision Records</em>, then spawns a short-lived LLM agent whose job is to judge whether your code changes meet each ADR.<br><br>The team's <em>processes</em> matter more than the tool itself — adr-lint just makes the process automatable.<br><br>I applied the same principle when writing a published article on AI and trust: <em>15 ADRs</em> defined the boundaries before a single sentence was written, and one agent per ADR independently reviewed each of <em>22 drafts</em>. Open source." },
  },
  {
    sv: { tag: "Meta", title: "Detta CV", description: "Du är inne i projektet just nu. Jag har tillämpat discipliner som <em>testdriven utveckling</em> för att säkerställa att det inte uppstår regressioner när jag gör ändringar — och lagt stor vikt vid att leverera en engagerande upplevelse snarare än bara ännu en generisk sajt.<br><br>Det utmanade verkligen min kreativitet. Jag känner mig genuint tacksam för att ha jobbat med så många duktiga UX-personer som gav mig en solid grund att stå på." },
    en: { tag: "Meta", title: "This CV", description: "You're inside the project right now. I've enforced disciplines like <em>test-driven development</em> to ensure there are no regressions as I make changes — and put real emphasis on delivering a compelling experience rather than just another generic website.<br><br>That really challenged my creativity. I feel truly blessed to have worked with so many talented UX people who gave me a solid foundation to stand on." },
  },
  {
    sv: { tag: "Open Source", title: "TDD-kommandogenerator", description: "För mig var nyckelingrediensen i AI-assisterad kodning att leverera arbete med <em>hög kvalitet</em>. Mitt svar var <em>testdriven utveckling</em> — ett sätt att skapa kontrakt för sin mjukvara och säkerställa att förändringarna uppfyller kriterierna från början.<br><br>Eftersom AI-kodningsagenter inte är tränade på TDD-metodik skapade jag <em>slash-kommandon</em> — återanvändbara promptmallar så att man slipper upprepa sig varje session.<br><br>Jag open source:ade allt och fick <em>över 100 GitHub-stjärnor över en natt</em>. Repot har 100% testtäckning och innehåller en generator som låter dig anpassa var kommandona installeras." },
    en: { tag: "Open Source", title: "TDD Command Generator", description: "For me, the key ingredient in AI-assisted coding was delivering <em>high quality work</em>. My answer was <em>test-driven development</em> — a way to create contracts for your software and ensure that changes actually meet the criteria from the beginning.<br><br>Since AI coding agents aren't trained on TDD practices, I created <em>slash commands</em> — reusable prompt templates so you don't repeat yourself every session.<br><br>I open sourced everything and received <em>over 100 GitHub stars overnight</em>. The repo has 100% test coverage and features a generator that lets you customize where to install the commands." },
  },
  {
    sv: { tag: "Open Source", title: "obscene", description: "Copy-paste-kod är notoriskt svår att se i en kodbas — den smyger sig in över tid, och ingen vill peka finger. Så jag byggde <em>obscene</em>, ett verktyg som på ett neutralt sätt visar beteendemönster i din kod och pekar ut tydliga <em>refaktoriseringsmöjligheter</em>.<br><br>Tanken är att ta bort den sociala friktionen — istället för att en utvecklare ska säga \"den här koden borde städas\", visar verktyget mönstren och låter teamet besluta tillsammans.<br><br>Open source, byggd för att bo i CI eller köras lokalt." },
    en: { tag: "Open Source", title: "obscene", description: "Copy-paste code is notoriously hard to see in a codebase — it creeps in over time and nobody wants to point fingers. So I built <em>obscene</em>, a tool that neutrally surfaces behavior patterns in your code and highlights clear <em>refactor opportunities</em>.<br><br>The idea is to remove the social friction — instead of one developer saying \"this should be cleaned up\", the tool shows the patterns and lets the team decide together.<br><br>Open source, built to live in CI or run locally." },
  },
  {
    sv: { tag: "Open Source", title: "cc-ping", description: "Claude Code har vecko- och sessionsgränser som återställs vid specifika tidpunkter. Att hålla koll på exakt när blir snabbt en mental belastning — speciellt om man jonglerar flera konton.<br><br><em>cc-ping</em> \"pingar\" ett eller flera Claude Code-konton åt dig så att gränserna återställs så tidigt som möjligt. Det kan också vara smart — och se till att din sessionsgräns återställs precis lagom till mitten av din arbetsdagspeak.<br><br>Liten, fokuserad, open source. Ett av flera verktyg jag byggt för att hantera AI-agenter dagligen." },
    en: { tag: "Open Source", title: "cc-ping", description: "Claude Code has weekly and session limits that reset at specific times. Tracking exactly when becomes a cognitive load fast — especially if you're juggling several accounts.<br><br><em>cc-ping</em> \"pings\" one or more Claude Code accounts for you so the limits reset as early as possible. It can also be smart — arranging your session limit to reset right around the middle of your workday peak.<br><br>Small, focused, open source. One of several tools I've built for managing AI agents day-to-day." },
  },
  {
    sv: { tag: "Open Source", title: "Me and My Crew", description: "När jag jobbar med AI-agenter i terminalen vill jag hellre <em>se</em> dem jobba än ha dem dolda i bakgrunden. Bakgrundsagenter sliter på fokuset — du måste hela tiden komma ihåg att kolla in dem.<br><br><em>Me and My Crew</em> är min publika version av min Gas Town-uppsättning — ett sätt att enkelt orkestrera flera agenter sida vid sida i terminalen, med tydlig struktur för vem som gör vad.<br><br>Det är ingen produkt — det är ett \"så här satte jag upp det, om du vill replikera\". <a href=\"https://github.com/wbern/gastown-me-and-my-crew\" target=\"_blank\" rel=\"noopener noreferrer\">github.com/wbern/gastown-me-and-my-crew</a>" },
    en: { tag: "Open Source", title: "Me and My Crew", description: "When I work with AI agents in the terminal, I'd rather <em>see</em> them work than have them hidden in the background. Background agents tax focus — you have to keep remembering to check on them.<br><br><em>Me and My Crew</em> is my public version of my Gas Town setup — a way to easily orchestrate several agents side by side in the terminal, with clear structure for who does what.<br><br>It's not a product — it's a \"here's how I set this up if you want to replicate\". <a href=\"https://github.com/wbern/gastown-me-and-my-crew\" target=\"_blank\" rel=\"noopener noreferrer\">github.com/wbern/gastown-me-and-my-crew</a>" },
  },
  {
    sv: { tag: "Open Source", title: "tmux-explode", description: "När jag kör många agenter parallellt via tmux ville jag ibland bara luta mig tillbaka och titta — se allt på en gång, utan att hoppa mellan sessioner.<br><br><em>tmux-explode</em> är ett litet kommando som visar alla mina tmux-sessioner i en enda ruta. Det blir lite som ett <em>kontrolltorn</em> för agentarbete.<br><br>Open source. Byggd för min egen workflow, men sannolikt användbar för alla som kör många agenter." },
    en: { tag: "Open Source", title: "tmux-explode", description: "When I run many agents in parallel via tmux, I sometimes just want to lean back and watch — see everything at once without jumping between sessions.<br><br><em>tmux-explode</em> is a small command that displays all of my tmux sessions in a single pane. It feels a bit like a <em>control tower</em> for agent work.<br><br>Open source. Built for my own workflow, but likely useful to anyone running many agents." },
  },
  {
    sv: { tag: "Personligt projekt", title: "Chess Reel", description: "Jag byggde ursprungligen detta för att lära min son Hyper-Accelerated Dragon-varianten av Sicilianskt som svart — ett schackbräde som spelar reels.<br><br>Jag byggde det med <em>testdriven utveckling</em> och de klassiska tre testnivåerna, där jag upptäckte att en <em>diamantformad testsvit</em> — med många fler något tyngre tester — var mycket fördelaktig för agentisk kodning.<br><br>Jag tacklade komplexiteten i att LLM:er inte kan spela schack genom att förstå schackprotokoll och grundläggande principer. Ett roligt fritidsprojekt som lärt mig mycket om hur man hanterar <em>stora mängder AI-skriven kod från grunden</em>." },
    en: { tag: "Personal Project", title: "Chess Reel", description: "I originally built this to teach my son the Hyper-Accelerated Dragon variation of the Sicilian as black — a chess board that plays reels.<br><br>I built it using <em>test-driven development</em> with the classic three tiers of testing, where I discovered that a <em>diamond-shaped test suite</em> — with many more slightly heavier tests — was quite beneficial for agentic coding.<br><br>I tackled the complexity of how LLMs can't play chess by understanding chess protocols and foundational principles. A fun spare-time project that taught me a lot about managing <em>large amounts of AI-written code from the bottom up</em>." },
  },
  {
    sv: { tag: "Undervisning", title: "TDD med AI — Presentation", description: "En presentation om hur man gör TDD med AI, skapad helt från terminalen med Claude Code. Jag använde <em>Slidev</em> för att bygga slides som hostas på min webbsajt — alltid tillgängliga och redo att köras." },
    en: { tag: "Teaching", title: "TDD with AI — Presentation", description: "A presentation on how to do TDD with AI, built entirely from the terminal with Claude Code. I used <em>Slidev</em> to create slides hosted on my website — always accessible and ready to present." },
  },
  {
    sv: { tag: "Dataanalys", title: "LinkedIn-konversationsanalys", description: "Jag får många oförfrågade kontaktförfrågningar på LinkedIn. Under 2025 bestämde jag mig för att <em>säga hej till alla som kontaktade mig</em>, oavsett vem de var.<br><br>Ungefär <em>hälften kände ett behov av att svara</em> och förklara varför de hade skickat en förfrågan — jag bröt en norm och utlöste samma sociala förväntan som i andra kommunikationskanaler.<br><br>Jag exporterade mina konversationer, kategoriserade dem i <em>13 kategorier</em> och byggde en interaktiv dashboard med <em>7 visualiseringar</em> för att hitta mönster i vem jag borde lägga mer tid på." },
    en: { tag: "Data Analysis", title: "LinkedIn Conversation Analysis", description: "I receive a lot of unsolicited connection requests on LinkedIn. In 2025 I decided to <em>say hello to everyone who connected with me</em>, regardless of who they were.<br><br>Around <em>half felt the need to reply</em> and explain why they'd sent a request — I was breaking a norm, triggering the same social expectation as any other communication channel.<br><br>I exported my conversations, categorized them into <em>13 categories</em>, and built an interactive dashboard with <em>7 visualizations</em> to find patterns in who I should spend more time with." },
  },
  {
    sv: { tag: "3D-visualisering", title: "Arkitektritning till 3D", description: "Jag frågade två arkitekter hur de visualiserar sina ritningar för kunder. De sa att det finns sätt, men att det är omständligt. Så jag ville försöka bygga en <em>3D-visualisering från en av deras CAD-ritningar</em> och se hur långt jag kunde ta det utan att detaljstyra det visuella resultatet.<br><br>Idén var att bara ta datan från AutoCAD och göra om den till 3D — skapa en pipeline där varje steg utförs med hjälp av en <em>LLM-agent</em> för att generera en slutgiltig 3D-återgivning av ritningen.<br><br>3D är ett utmanande område för agentisk kodning, men det kanske mest insiktsfulla var att <em>området fortfarande är fullt av proprietära assets och mjukvara</em>. Det lärde mig mycket om gränserna för vad agenter kan och inte kan göra när ekosystemet inte är öppet." },
    en: { tag: "3D Visualization", title: "Architectural Blueprint to 3D", description: "I asked two architects how they visualize their blueprints for clients. They said there were ways, but it's cumbersome. So I wanted to try building a <em>3D visualization from one of their CAD blueprints</em> and see how far I could take it without micromanaging the visual output.<br><br>The idea was to only take the data from AutoCAD and turn it into 3D — creating a pipeline where each step is executed with the help of an <em>LLM agent</em> to generate a final 3D rendition of the blueprint.<br><br>3D is a challenging space for agentic coding, but what was perhaps most insightful was that <em>the space is still crowded with proprietary assets and software</em>. It taught me a lot about the boundaries of what agents can and can't do when the ecosystem isn't open." },
  },
  {
    sv: { tag: "Spel", title: "Pixi Platformer", description: "Jag ville bygga ett spel från grunden — inte med en spelmotor, utan med <em>webbteknologi</em>. Resultatet blev en platformer i Doodle Jump-stil med en egen <em>Entity Component System</em>-arkitektur i React, där varje spelobjekt sätts ihop av lösa komponenter: position, hastighet, kollision, soliditet.<br><br>Fysiken använder <em>icke-linjär gravitation</em> med olika accelerationskurvor för uppåt- och nedåtrörelse. Spelet stöder både <em>tangentbord och touch</em>, renderat med <em>Pixi.js 7</em> via WebGL och testat med <em>Vitest</em>." },
    en: { tag: "Game", title: "Pixi Platformer", description: "I wanted to build a game from scratch — not with a game engine, but with <em>web technology</em>. The result is a Doodle Jump-style platformer with a custom <em>Entity Component System</em> architecture in React, where each game object is composed of loose components: position, velocity, collision, solidity.<br><br>The physics use <em>non-linear gravity</em> with different acceleration curves for upward and downward movement. The game supports both <em>keyboard and touch</em>, rendered with <em>Pixi.js 7</em> via WebGL and tested with <em>Vitest</em>." },
  },
  {
    sv: { tag: "AI / RAG", title: "Knowledge Bot", description: "En kund inom fastighetsförvaltning fick tusentals supportmejl och svarade på samma frågor om och om igen. Ny personal hade ingen aning om hur liknande ärenden hade hanterats tidigare — kunskapen fanns begravd i <em>38 000 gamla mejl</em>.<br><br>Jag byggde en RAG-baserad mejlrådgivare som kombinerar <em>hybridsökning</em> — BM25 nyckelordssökning via SQLite FTS5 och vektorsökning via <em>LEANN</em>, ett grafbaserat retrieval-system som komprimerar lagringen med 97%. Resultaten slås ihop med <em>Reciprocal Rank Fusion</em> och matas till en lokal LLM via <em>Ollama</em>.<br><br>Systemet gick från 40% till <em>100% träffsäkerhet</em> efter att jag lade till metadataprefix och hybridstrategin. Det körs helt privat på en <em>Proxmox-VM</em> provisionerad med Ansible — ingen data lämnar kundens servrar. En <em>Telegram-bot</em> och en mejlbevakare ger personalen rådgivning i realtid, med källhänvisningar till vilka historiska mejl som låg till grund för svaret." },
    en: { tag: "AI / RAG", title: "Knowledge Bot", description: "A property management client received thousands of support emails and kept answering the same questions repeatedly. New staff had no idea how similar cases had been handled — the knowledge was buried in <em>38,000 old emails</em>.<br><br>I built a RAG-based email advisor combining <em>hybrid search</em> — BM25 keyword search via SQLite FTS5 and vector search via <em>LEANN</em>, a graph-based retrieval system that compresses storage by 97%. Results are merged using <em>Reciprocal Rank Fusion</em> and fed to a local LLM through <em>Ollama</em>.<br><br>The system went from 40% to <em>100% retrieval accuracy</em> after adding metadata prefixes and the hybrid strategy. It runs entirely private on a <em>Proxmox VM</em> provisioned with Ansible — no data leaves the client's servers. A <em>Telegram bot</em> and an email watcher provide staff with real-time advice, with source citations showing which historical emails informed the response." },
  },
  {
    sv: { tag: "Legacymigrering", title: "Telia.se", description: "Telia.se kördes på ett legacysystem byggt i <em>Freemarker</em> — en mallmotor som var djupt sammanflätad med affärslogiken. Jag skapade en rad kreativa lösningar för att migrera systemet steg för steg till en modern frontend utan att behöva göra en big bang-omskrivning.<br><br>Det innebar att bygga bryggor mellan gammalt och nytt, införa nya mönster som kunde samexistera med den befintliga kodbasen, och successivt fasa ut Freemarker-mallar utan att störa produktionen. Mycket av arbetet handlade om att hitta pragmatiska kompromisser — <em>migrera utan att stanna</em>." },
    en: { tag: "Legacy Migration", title: "Telia.se", description: "Telia.se ran on a legacy system built in <em>Freemarker</em> — a templating engine deeply intertwined with the business logic. I created a range of creative solutions to migrate the system incrementally to a modern frontend without requiring a big bang rewrite.<br><br>This meant building bridges between old and new, introducing patterns that could coexist with the existing codebase, and progressively phasing out Freemarker templates without disrupting production. Much of the work was about finding pragmatic compromises — <em>migrate without stopping</em>." },
  },
  {
    sv: { tag: "Företag", title: "kendev.se", description: "Min konsultfirmas webbplats. IT-integration, coachning och migration — <em>\"Äter du förändring till frukost?\"</em><br><br><a href=\"https://www.kendev.se\" target=\"_blank\" rel=\"noopener noreferrer\">www.kendev.se</a>" },
    en: { tag: "Business", title: "kendev.se", description: "My consultancy's website. IT integration, coaching, and migration — <em>\"Do you eat change for breakfast?\"</em><br><br><a href=\"https://www.kendev.se\" target=\"_blank\" rel=\"noopener noreferrer\">www.kendev.se</a>" },
  },
  {
    sv: { tag: "Ledarskap", title: "Sembo.se Startsida", description: "Sembo.se:s startsida började som ett litet experiment — en enkel sida med begränsad funktionalitet. Jag tog den från det stadiet till en <em>förstklassig användarupplevelse</em> tillsammans med mitt team på Sembo som jag ledde.<br><br>Det innebar att omforma arkitekturen, förbättra prestanda och skapa en sammanhållen design som matchade resten av plattformen. Jag drev arbetet framåt genom att <em>coacha teamet</em>, sätta tekniska standarder och se till att vi levererade iterativt med hög kvalitet.<br><br>Startsidan blev en central yta för <em>kampanjer, inspirationsinnehåll och snabb resebokning</em> — och ett bevis på vad ett litet, fokuserat team kan åstadkomma med rätt ledarskap och tydliga mål." },
    en: { tag: "Leadership", title: "Sembo.se Startpage", description: "The Sembo.se startpage began as a cute early experiment — a simple page with limited functionality. I transformed it into a <em>first-class user experience</em> together with my team at Sembo that I led.<br><br>This meant rearchitecting the page, improving performance, and creating a cohesive design that matched the rest of the platform. I drove the work forward by <em>coaching the team</em>, setting technical standards, and ensuring we delivered iteratively with high quality.<br><br>The startpage became a key surface for <em>campaigns, inspirational content, and quick travel booking</em> — and proof of what a small, focused team can accomplish with the right leadership and clear goals." },
  },
];

export function getProjects(lang: Lang): Project[] {
  return projectEntries.map((entry) => entry[lang]);
}

/** Generate a URL slug from an English project title. */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/** Get URL slugs derived from English project titles (stable, locale-independent). */
export function getProjectSlugs(): string[] {
  return projectEntries.map((entry) => slugify(entry.en.title));
}

export { projectEntries };
