import type { Lang } from "./ui";

export interface Project {
  tag: string;
  title: string;
  description: string;
}

interface ProjectEntry {
  sv: Project;
  en: Project;
}

const projectEntries: ProjectEntry[] = [
  {
    sv: { tag: "AI-agent", title: "Community Assistant", description: "Min bostadsrättsförening fick samma frågor om och om igen via mejl. Alla förfrågningar sparas som ärenden, men att hitta tidigare svar och skriva nya blev en verklig arbetsbelastning för en av våra styrelsemedlemmar.<br><br>Jag byggde en AI-assistent som plockar upp inkommande mejl, matchar dem mot tidigare ärenden och <em>föreslår ett svar</em> baserat på hur styrelsen svarat förut. Styrelsemedlemmen godkänner eller ändrar — klart.<br><br>Byggt på <em>Akka SDK</em> med event sourcing, integrerat med <em>Gmail</em> och <em>Google Sheets</em>. En <em>SmolLM2-135M</em> nano-LLM hanterar jobbet — tillräckligt lätt för att inte kräva en stor modell.<br><br>För testning byggde jag en <em>3-stegs-strategi</em>: dummy-LLM:er som returnerar exakt det svar jag vill ha (snabbt, deterministiskt), SmolLM2 nano-modellen som realistiskt mellanlager, och produktionsmodellen för slutlig kvalitetskontroll. Varje steg benchmarkar nästa." },
    en: { tag: "AI Agent", title: "Community Assistant", description: "My housing community kept receiving the same questions by email. All inquiries are filed as tickets, but finding previous answers and drafting replies was becoming a real workload for one of our board members.<br><br>I built an AI assistant that picks up incoming emails, matches them against previous tickets, and <em>suggests a reply</em> based on how the board answered before. The board member approves or amends — that's it.<br><br>Built on the <em>Akka SDK</em> with event sourcing, integrated with <em>Gmail</em> and <em>Google Sheets</em>. A <em>SmolLM2-135M</em> nano LLM handles the job — light enough to not need a large model.<br><br>For testing, I built a <em>3-tier strategy</em>: dummy LLMs that return exactly the response I want (fast, deterministic), the SmolLM2 nano model as a realistic middle tier, and the production model for final confidence checks. Each tier benchmarks the next." },
  },
  {
    sv: { tag: "Infrastruktur", title: "Pi-PAI", description: "Det började med att jag ville köra Claude Code på distans — och insåg att en <em>Raspberry Pi</em> kunde hantera det mesta av mitt rutinarbete. Jag satte upp fjärrstyrd agentorkestrering på en Pi 4 och styrde det från mobilen via en app som heter <em>Happy</em>, som också gav mig röststyrning. Det kändes futuristiskt. Föreställ dig att köra bil och dirigera din AI-besättning som om du stod på bryggan på ett rymdskepp.<br><br>Jag byggde en <em>MCP-server</em> som kontrollplan: en Claude Code-instans som kunde starta och stoppa andra Claude Code-sessioner baserat på vad som behövde göras. Varje agent hade tillgång till <em>GitHub</em> och kunde självständigt köra tester, skapa pull requests och fortsätta arbeta medan jag var borta från datorn.<br><br>Hela setupen provisioneras med <em>Ansible</em> — reproducerbar infrastruktur som jag kan deploya på kraftigare hårdvara, fler maskiner eller hos en kund." },
    en: { tag: "Infrastructure", title: "Pi-PAI", description: "It started with wanting to run Claude Code remotely — and realizing a <em>Raspberry Pi</em> could handle most of my menial work. I set up remote agent orchestration on a Pi 4 and accessed it from my phone through an app called <em>Happy</em>, which also gave me voice control. It felt futuristic. Imagine driving your car and directing your AI crew like you're on the bridge of a starship.<br><br>I built an <em>MCP server</em> as a control plane: one Claude Code instance that could start and stop other Claude Code sessions based on what needed to be done. Each agent had access to <em>GitHub</em> and could independently run tests, create pull requests, and keep working while I was away from the computer.<br><br>The whole setup is provisioned with <em>Ansible</em> — reproducible infrastructure I can redeploy on bigger hardware, more machines, or at a client site." },
  },
  {
    sv: { tag: "Legacyräddning", title: "DLL-dekompilering", description: "En kund startade om sin servermjukvara var 15:e minut. Orsaken: ett kritiskt <em>race condition</em> i underhållslösa leverantörs-DLL:er — och det fanns ingen källkod.<br><br>Jag körde en dekompilator på DLL-filerna, vilket gav källkod som var ungefär 80% korrekt — resten trasigt på grund av binärernas ålder. Sedan en <em>3-fasprocess</em>: först byggde jag en testsvit mot den befintliga setupen som verifierade all mjukvarans funktionalitet. Sedan fixade jag den dekompilerade koden tills varje test passerade. Slutligen genomförde jag planen för att lösa själva samtidighetsproblemet.<br><br>Det fungerade — och låste upp en betydande intäktsström för min kund. Deployad via <em>Tailscale</em> till <em>5 kundsajter</em> med 3 rollback-strategier." },
    en: { tag: "Legacy Rescue", title: "DLL Decompilation", description: "A client was restarting their server software every 15 minutes. The cause: a critical <em>race condition</em> in unmaintained vendor DLLs — and there was no source code.<br><br>I ran a decompiler on the DLLs, which produced source code that was roughly 80% correct — the rest broken by the age of the binaries. Then a <em>3-phase process</em>: first, I built a test suite against the existing setup that asserted all the software's functionality. Second, I fixed the decompiled code until every test passed. Third, I executed the plan for solving the concurrency issue itself.<br><br>It worked — and unlocked a significant revenue stream for my client. Deployed over <em>Tailscale</em> to <em>5 customer sites</em> with 3 rollback strategies." },
  },
  {
    sv: { tag: "Modernisering", title: "Legacy-schackverktyg: omskrivning", description: "Jag skulle använda ett verktyg för att lotta ett schackturneringsfält. När jag försökte ladda ner det var det inte tillgängligt längre. Verktyget hade varit legacy sedan 2018, men det används fortfarande av många klubbar för sin enkelhet. <em>Lottning i schack är förvånansvärt komplicerat</em> — algoritmerna som bestämmer parningar är mjukvarans kärnvärde.<br><br>Jag hittade desktopappen på min dator och insåg: det här borde finnas på webben. Källkoden levererades med mjukvaran, så jag kopplade isär frontenden från databasoperationerna och skapade en webbsajt som interagerade via ett REST-lager med den ursprungliga Java-lottningslogiken.<br><br>Sedan byggde jag <em>snapshot-tester av alla möjliga lottningspermutationer</em> — över 200 snapshots av hur databasen förändras under en turnering. När skyddsnätet var på plats bad jag min kodningsagent att porta hela backenden till frontenden med <em>sql.js</em>. Jag vaknade på morgonen till att allt var klart och verifierat fungerande. Hela applikationen körs nu <em>offline i webbläsaren</em> — ingen backend behövs." },
    en: { tag: "Modernization", title: "Legacy Chess Tool Rewrite", description: "I was going to use a tool to seed a chess tournament. When I went to download it, it wasn't available anymore. The tool had been legacy since 2018, but it's still used by many clubs for its simplicity. <em>Seeding in chess is surprisingly complicated</em> — the algorithms that determine pairings are the core value of this software.<br><br>I found the desktop app on my machine and realized: this should be on the web so anyone can access it without running Java. The source code was shipped with the software, so I decoupled the frontend from the database operations and created a website interacting through a REST layer with the original Java seeding logic.<br><br>Then I built <em>snapshot tests of all possible seeding permutations</em> — over 200 snapshots of how the database changes during a tournament. Once that safety net was in place, I asked my coding agent to port the entire backend into the frontend with <em>sql.js</em>. I woke up in the morning to it being completely finished and verified working. The whole application now runs <em>offline in the browser</em> — no backend needed." },
  },
  {
    sv: { tag: "Skrivande", title: "Automatiserad artikelvalidering genom beslutsdokument", description: "\"LLM-produktivitetsdebatten är över. <em>Den verkliga flaskhalsen är tillitsbyggande.</em>\" Det var öppningen av en artikel jag fick i uppdrag att skriva och skicka in till en publikation om hur AI möjliggör bättre arbete.<br><br>Slutmålen var redan definierade. Så jag fångade varje mål som ett <em>Architecture Decision Record</em>. 15 ADR:er totalt, som definierade ramarna innan en enda mening var skriven.<br><br>Sedan lät jag min kodningsagent skriva initiala utkast som försökte uppfylla dessa beslutsdokument. När jag itererade lutade jag mig tillbaka på ADR:erna — jag skapade ett <em>verktyg som startar en LLM-agent för varje beslutsdokument</em>, var och en granskar utkastet oberoende mot det ADR:ets förväntningar. <em>22 utkast</em> totalt.<br><br>Det skapade ett tydligt ramverk för att hålla fokus med extremt få ord. Jag har sedan dess tillämpat samma princip på kod — med beslutsdokument för att säkerställa att koden lever upp till förväntningarna hos de som underhåller systemet." },
    en: { tag: "Technical Writing", title: "Automated Article Validation Through Decision Records", description: "\"The LLM productivity debate is over. <em>The real bottleneck is trust-building.</em>\" That was the opening of an article I was tasked with writing and submitting to a publication on how AI enables better work.<br><br>The end goals were already defined. So I captured each one as an <em>Architecture Decision Record</em>. 15 ADRs total, defining the boundaries before writing a single sentence.<br><br>Then I let my coding agent write initial drafts trying to meet those decision records. As I iterated, I leaned back on the ADRs — I created a <em>tool that spawns an LLM agent for each decision record</em>, each one independently reviewing the draft against that ADR's expectations. <em>22 drafts</em> total.<br><br>This created a clear framework for staying on point with extremely few words. I've since applied the same principle to code — using decision records to ensure code lives up to the expectations of the people maintaining the system." },
  },
  {
    sv: { tag: "Meta", title: "Detta CV", description: "Du är inne i projektet just nu. Vem som helst kan skapa en webbsajt nuförtiden med vibe coding — och den här sajten är inget undantag. <em>Jag har inte skrivit en enda rad kod själv.</em><br><br>Däremot har jag tillämpat discipliner som <em>testdriven utveckling</em> för att säkerställa att det inte uppstår regressioner när jag gör ändringar. Och medan vem som helst kan skapa en webbsajt är det viktigare än någonsin att leverera en engagerande upplevelse snarare än att ge användarna något som matats till en LLM en miljon gånger.<br><br>Det utmanade verkligen min kreativitet. Jag har aldrig sett UX som min starka sida, men jag känner mig genuint tacksam för att ha jobbat med så många duktiga UX-personer som gav mig en solid grund att stå på när det gäller att möjliggöra en bra användarupplevelse." },
    en: { tag: "Meta", title: "This CV", description: "You're inside the project right now. Anyone can create a website these days with vibe coding — and this website is no exception. <em>I haven't written a single line of code myself.</em><br><br>However, I've enforced disciplines like <em>test-driven development</em> to ensure there are no regressions as I make changes. And while anyone can create a website, it's more important than ever to provide a compelling experience rather than just giving users something that's been fed to an LLM a million times over.<br><br>That really challenged my creativity. I've never considered UX to be my strong suit, but I feel truly blessed to have worked with so many talented UX people who gave me a solid foundation to stand on when it comes to enabling a great user experience." },
  },
  {
    sv: { tag: "Open Source", title: "TDD-kommandogenerator", description: "Precis som alla andra som börjat med AI-assisterad kodning skapar man till slut något slags ramverk för sin kommunikation med agenter. För mig var nyckelingrediensen att leverera arbete med <em>hög kvalitet</em>.<br><br>Det betyder inte alltid buggfritt — men för seriösa produkter ska befintliga funktioner inte gå sönder när man utvecklar nya, och man ska veta det förväntade resultatet. Mitt svar var <em>testdriven utveckling</em>. Det är ett sätt att skapa kontrakt för sin mjukvara och säkerställa — nästan som en vetenskapsman — att förändringarna uppfyller kriterierna från början.<br><br>Eftersom AI-kodningsagenter inte är tränade på TDD-metodik började jag samla bra korta förklaringar, vilket ledde till att jag skapade <em>slash-kommandon</em> — i princip glorifierad copy-paste så att man slipper upprepa sig varje session.<br><br>Jag open source:ade allt och fick <em>över 100 GitHub-stjärnor över en natt</em>. Repot har 100% testtäckning och innehåller en generator som låter dig anpassa var kommandona installeras. Generatorn har uppskattats — många har forkat det." },
    en: { tag: "Open Source", title: "TDD Command Generator", description: "Like everyone who's started doing AI-enabled coding, you end up creating some kind of framework for how to structure your communication with agents. For me, the key ingredient was delivering <em>high quality work</em>.<br><br>That doesn't always mean bug-free — but for serious products, your pre-existing features shouldn't break when you develop new ones, and you should know the expected outcome of whatever you're coding. My answer was <em>test-driven development</em>. It's a way to create contracts for your software and ensure — almost like a scientist — that the changes actually meet the criteria communicated from the beginning.<br><br>Since AI coding agents aren't implicitly trained on TDD practices, I started collecting good short-form explanations, which led to creating <em>slash commands</em> — basically glorified copy-paste so you don't repeat yourself every session.<br><br>I open sourced all of these and received <em>over 100 GitHub stars overnight</em>. The repo has 100% test coverage and features a generator that lets you customize where to install the commands and add specific behavior. The generator has been quite appreciated — plenty of people have forked it." },
  },
  {
    sv: { tag: "Personligt projekt", title: "Chess Reel", description: "Jag byggde ursprungligen detta för att lära min son Hyper-Accelerated Dragon-varianten av Sicilianskt som svart. Sedan blev det ett meme-orienterat schackbräde — ett schackbräde som spelar reels.<br><br>Jag startade hösten 2025 när AI-modeller fortfarande krävde nära övervakning. Jag byggde det med <em>testdriven utveckling</em> och de klassiska tre testnivåerna, där jag upptäckte att en <em>diamantformad testsvit</em> — med många fler något tyngre tester — var mycket fördelaktig för agentisk kodning.<br><br>Jag tacklade komplexiteten i att LLM:er inte kan spela schack genom att förstå schackprotokoll, grundläggande principer och varför vissa taktiker är mer intressanta än andra. Det gav många insikter.<br><br>Det här har varit ett riktigt roligt fritidsprojekt som lärt mig mycket om hur man hanterar <em>stora mängder kod skriven av AI från grunden</em>. 856 commits, 470 testfiler, 77 källfiler." },
    en: { tag: "Personal Project", title: "Chess Reel", description: "I originally built this to teach my son the Hyper-Accelerated Dragon variation of the Sicilian as black. Then it turned into a meme-oriented chess board — a chess board that plays reels.<br><br>I started this back in autumn 2025 when AI models still required close supervision. I built it using <em>test-driven development</em> with the classic three tiers of testing, where I discovered that a <em>diamond-shaped test suite</em> — with many more slightly heavier tests — was quite beneficial for agentic coding.<br><br>I tackled the complexity of how LLMs can't play chess by understanding chess protocols, foundational principles, and why certain tactics are more interesting than others. That provided a lot of insight.<br><br>This has been a really fun spare-time project that enabled me to learn a lot about how to deal with <em>large amounts of code written by AI from the bottom up</em>. 856 commits, 470 test files, 77 source files." },
  },
  {
    sv: { tag: "Undervisning", title: "TDD med AI — Presentation", description: "När jag skapade den här presentationen om hur man gör TDD med AI insåg jag att jag knappt lämnade terminalen där jag pratade med Claude Code. Det fanns egentligen ingen anledning att lämna terminalen för att skapa en presentation heller.<br><br>Jag hade alltid hört bra saker om <em>Slidev</em> och bestämde mig för att använda det för att snabbt piska ihop några slides som jag kunde hosta på min webbsajt och alltid komma åt — så att jag kunde köra min presentation när som helst med en dator till hands." },
    en: { tag: "Teaching", title: "TDD with AI — Presentation", description: "When I created this slideshow on how to do TDD with AI, I realized I was barely leaving the terminal where I was talking to Claude Code. There was really no reason to leave the terminal for creating a presentation either.<br><br>I'd always heard good things about <em>Slidev</em> and decided to use it to whip out a few slides I could host on my website and always access — so I could do my presentation with the flip of a coin and maybe a computer." },
  },
  {
    sv: { tag: "Dataanalys", title: "LinkedIn-konversationsanalys", description: "Jag får många oförfrågade kontaktförfrågningar på LinkedIn. Under 2025 bestämde jag mig för att vända på det och <em>säga hej till alla som kontaktade mig</em>, oavsett vem de var.<br><br>Resultaten var intressanta. Ungefär <em>hälften kände ett behov av att svara</em> och förklara varför de hade skickat en kontaktförfrågan. Jag bröt en norm — folk kopplar slumpmässigt på LinkedIn utan att säga något, och genom att plötsligt säga hej utlöste jag samma sociala förväntan som i alla andra kommunikationskanaler: de kände att de behövde förklara sig.<br><br>Utöver den kvalitativa feedbacken ville jag bygga statistik kring de huvudsakliga anledningarna till att folk kontaktar mig på LinkedIn — och i slutändan ta reda på <em>vem jag borde lägga mer tid på</em>. Jag exporterade mina konversationer, kategoriserade dem i <em>13 kategorier</em> och byggde en interaktiv dashboard med <em>7 visualiseringar</em> för att se mönstren." },
    en: { tag: "Data Analysis", title: "LinkedIn Conversation Analysis", description: "I receive a lot of unsolicited connection requests on LinkedIn. In 2025 I decided to flip the script and <em>say hello to everyone who connected with me</em>, regardless of who they were.<br><br>The results were interesting. Around <em>half the people felt the need to reply</em> and explain why they'd sent a connection request in the first place. I was breaking a norm — people randomly connect on LinkedIn without saying anything, and by suddenly saying hello I triggered the same social expectation as any other communication channel: they felt they had to explain themselves.<br><br>Beyond the qualitative feedback, I wanted to build statistics around the main reasons people contact me on LinkedIn — and ultimately figure out <em>who I should spend more time with</em>. I exported my conversations, categorized them into <em>13 categories</em>, and built an interactive dashboard with <em>7 visualizations</em> to see the patterns." },
  },
  {
    sv: { tag: "3D-visualisering", title: "Arkitektritning till 3D", description: "Jag frågade två arkitekter hur de visualiserar sina ritningar för kunder. De sa att det finns sätt, men att det är omständligt. Så jag ville försöka bygga en <em>3D-visualisering från en av deras CAD-ritningar</em> och se hur långt jag kunde ta det utan att detaljstyra det visuella resultatet.<br><br>Idén var att bara ta datan från AutoCAD och göra om den till 3D — skapa en pipeline där varje steg utförs med hjälp av en <em>LLM-agent</em> för att generera en slutgiltig 3D-återgivning av ritningen.<br><br>3D är ett utmanande område för agentisk kodning, men det kanske mest insiktsfulla var att <em>området fortfarande är fullt av proprietära assets och mjukvara</em>. Det lärde mig mycket om gränserna för vad agenter kan och inte kan göra när ekosystemet inte är öppet." },
    en: { tag: "3D Visualization", title: "Architectural Blueprint to 3D", description: "I asked two architects how they visualize their blueprints for clients. They said there were ways, but it's cumbersome. So I wanted to try building a <em>3D visualization from one of their CAD blueprints</em> and see how far I could take it without micromanaging the visual output.<br><br>The idea was to only take the data from AutoCAD and turn it into 3D — creating a pipeline where each step is executed with the help of an <em>LLM agent</em> to generate a final 3D rendition of the blueprint.<br><br>3D is a challenging space for agentic coding, but what was perhaps most insightful was that <em>the space is still crowded with proprietary assets and software</em>. It taught me a lot about the boundaries of what agents can and can't do when the ecosystem isn't open." },
  },
  {
    sv: { tag: "Spel", title: "Pixi Platformer", description: "Jag ville bygga ett spel från grunden — inte med en spelmotor, utan med <em>webbteknologi</em>. Resultatet blev en platformer i Doodle Jump-stil där en kaninkaraktär hoppar mellan procedurellt genererade plattformar.<br><br>Jag byggde en egen <em>Entity Component System</em>-arkitektur i React där varje spelobjekt sätts ihop av lösa komponenter: position, hastighet, kollision, soliditet. Systemen — fysik, tangentbord, touch, spawning — körs varje frame och opererar på dessa komponenter oberoende av varandra.<br><br>Fysiken använder <em>icke-linjär gravitation</em> med olika accelerationskurvor för uppåt- och nedåtrörelse, vilket ger hoppet en naturlig känsla. Kollisionsdetektering sker med AABB och hastighetsprediktion så att karaktären inte faller igenom plattformar.<br><br>Spelet stöder både <em>tangentbord och touch</em> — med svepdetektering som filtrerar bort oavsiktlig input. Renderat med <em>Pixi.js 7</em> via WebGL, testat med <em>Vitest</em> och <em>Storybook 9</em>, och deployat till <em>GitHub Pages</em>." },
    en: { tag: "Game", title: "Pixi Platformer", description: "I wanted to build a game from scratch — not with a game engine, but with <em>web technology</em>. The result is a Doodle Jump-style platformer where a bunny character jumps between procedurally generated platforms.<br><br>I built a custom <em>Entity Component System</em> architecture in React where each game object is composed of loose components: position, velocity, collision, solidity. The systems — physics, keyboard, touch, spawning — run every frame and operate on these components independently.<br><br>The physics use <em>non-linear gravity</em> with different acceleration curves for upward and downward movement, giving the jump a natural feel. Collision detection uses AABB with velocity prediction so the character doesn't clip through platforms.<br><br>The game supports both <em>keyboard and touch</em> — with swipe detection that filters out accidental input. Rendered with <em>Pixi.js 7</em> via WebGL, tested with <em>Vitest</em> and <em>Storybook 9</em>, and deployed to <em>GitHub Pages</em>." },
  },
  {
    sv: { tag: "AI / RAG", title: "Knowledge Bot", description: "En kund inom fastighetsförvaltning fick tusentals supportmejl och svarade på samma frågor om och om igen. Ny personal hade ingen aning om hur liknande ärenden hade hanterats tidigare — kunskapen fanns begravd i <em>38 000 gamla mejl</em>.<br><br>Jag byggde en RAG-baserad mejlrådgivare som kombinerar <em>hybridsökning</em> — BM25 nyckelordssökning via SQLite FTS5 och vektorsökning via <em>LEANN</em>, ett grafbaserat retrieval-system som komprimerar lagringen med 97%. Resultaten slås ihop med <em>Reciprocal Rank Fusion</em> och matas till en lokal LLM via <em>Ollama</em>.<br><br>Systemet gick från 40% till <em>100% träffsäkerhet</em> efter att jag lade till metadataprefix och hybridstrategin. Det körs helt privat på en <em>Proxmox-VM</em> provisionerad med Ansible — ingen data lämnar kundens servrar. En <em>Telegram-bot</em> och en mejlbevakare ger personalen rådgivning i realtid, med källhänvisningar till vilka historiska mejl som låg till grund för svaret." },
    en: { tag: "AI / RAG", title: "Knowledge Bot", description: "A property management client received thousands of support emails and kept answering the same questions repeatedly. New staff had no idea how similar cases had been handled — the knowledge was buried in <em>38,000 old emails</em>.<br><br>I built a RAG-based email advisor combining <em>hybrid search</em> — BM25 keyword search via SQLite FTS5 and vector search via <em>LEANN</em>, a graph-based retrieval system that compresses storage by 97%. Results are merged using <em>Reciprocal Rank Fusion</em> and fed to a local LLM through <em>Ollama</em>.<br><br>The system went from 40% to <em>100% retrieval accuracy</em> after adding metadata prefixes and the hybrid strategy. It runs entirely private on a <em>Proxmox VM</em> provisioned with Ansible — no data leaves the client's servers. A <em>Telegram bot</em> and an email watcher provide staff with real-time advice, with source citations showing which historical emails informed the response." },
  },
  {
    sv: { tag: "Legacymigrering", title: "Telia.se", description: "Telia.se kördes på ett legacysystem byggt i <em>Freemarker</em> — en mallmotor som var djupt sammanflätad med affärslogiken. Jag skapade en rad kreativa lösningar för att migrera systemet steg för steg till en modern frontend utan att behöva göra en big bang-omskrivning.<br><br>Det innebar att bygga bryggor mellan gammalt och nytt, införa nya mönster som kunde samexistera med den befintliga kodbasen, och successivt fasa ut Freemarker-mallar utan att störa produktionen. Mycket av arbetet handlade om att hitta pragmatiska kompromisser — <em>migrera utan att stanna</em>." },
    en: { tag: "Legacy Migration", title: "Telia.se", description: "Telia.se ran on a legacy system built in <em>Freemarker</em> — a templating engine deeply intertwined with the business logic. I created a range of creative solutions to migrate the system incrementally to a modern frontend without requiring a big bang rewrite.<br><br>This meant building bridges between old and new, introducing patterns that could coexist with the existing codebase, and progressively phasing out Freemarker templates without disrupting production. Much of the work was about finding pragmatic compromises — <em>migrate without stopping</em>." },
  },
  {
    sv: { tag: "Ledarskap", title: "Sembo.se Startsida", description: "Sembo.se:s startsida började som ett litet experiment — en enkel sida med begränsad funktionalitet. Jag tog den från det stadiet till en <em>förstklassig användarupplevelse</em> tillsammans med mitt team på Sembo som jag ledde.<br><br>Det innebar att omforma arkitekturen, förbättra prestanda och skapa en sammanhållen design som matchade resten av plattformen. Jag drev arbetet framåt genom att <em>coacha teamet</em>, sätta tekniska standarder och se till att vi levererade iterativt med hög kvalitet.<br><br>Startsidan blev en central yta för <em>kampanjer, inspirationsinnehåll och snabb resebokning</em> — och ett bevis på vad ett litet, fokuserat team kan åstadkomma med rätt ledarskap och tydliga mål." },
    en: { tag: "Leadership", title: "Sembo.se Startpage", description: "The Sembo.se startpage began as a cute early experiment — a simple page with limited functionality. I transformed it into a <em>first-class user experience</em> together with my team at Sembo that I led.<br><br>This meant rearchitecting the page, improving performance, and creating a cohesive design that matched the rest of the platform. I drove the work forward by <em>coaching the team</em>, setting technical standards, and ensuring we delivered iteratively with high quality.<br><br>The startpage became a key surface for <em>campaigns, inspirational content, and quick travel booking</em> — and proof of what a small, focused team can accomplish with the right leadership and clear goals." },
  },
];

export function getProjects(lang: Lang): Project[] {
  return projectEntries.map((entry) => entry[lang]);
}

/** Generate a URL slug from an English project title. */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/** Get URL slugs derived from English project titles (stable, locale-independent). */
export function getProjectSlugs(): string[] {
  return projectEntries.map((entry) => slugify(entry.en.title));
}

export { projectEntries };
